version: "3.9"
services:
  sao_app:
    build: .
    container_name: sao_app
    ports:
      - "5000:80"
  sao_db:
    container_name: sao_db
    ports:
      - '1521:1521'
    environment:
      - ORACLE_PASSWORD=orpassword
    image: gvenzl/oracle-xe