version: "3.9"

volumes:
  oracle_volume:

services:
  sao_aspnet:
    build: ./asp.net
    container_name: sao_aspnet
    ports:
      - "5074:5074"
    environment:
      DB: ${DB}
      DBUSER: ${DBUSER}
      DBUSERPASS: ${DBUSERPASS}
      DOTNET_WATCH_RESTART_ON_RUDE_EDIT: 'true'
    volumes:
      - ./asp.net:/aspnet
  sao_svelte:
    build: ./svelte
    container_name: sao_svelte
    ports:
      - "5173:5173"
    volumes:
      - ./svelte:/svelte
      - /svelte/node_modules
  sao_oracle:
    container_name: sao_oracle
    ports:
      - '1521:1521'
    environment:
      ORACLE_PASSWORD: ${DBPASS}
      APP_USER: ${DBUSER}
      APP_USER_PASSWORD: ${DBUSERPASS}
    volumes:
      - oracle_volume:/opt/oracle/oradata
    image: gvenzl/oracle-xe
